version: "3"

services:
  nginx:
    image: nginx:1.17.8
    container_name: my-nginx
    hostname: docker-nginx
    volumes:
      - ./www/a:/usr/share/nginx/html
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
    ports:
      - 8080:80
    environment:
      TZ: Asia/Shanghai    
