version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: my-mysql
    volumes: 
      - ./mysql-data:/var/lib/mysql
    ports: 
      - 13306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
